# Generated by Django 2.2.1 on 2019-06-24 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Locationdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=90)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modellearning.Personname')),
            ],
        ),
        migrations.CreateModel(
            name='Jobdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=90)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modellearning.Personname')),
            ],
        ),
    ]
